# Site settings
title: えぬえす工房
description: えぬえす工房
baseurl: ""
tags_path: "/blog/tags/"
#url:
top_url: "https://www.ns-koubou.com"

sass:
  style: compressed

# Build settings
excerpt_separator: "<!--more-->"

markdown: kramdown
highlighter: nil

kramdown:
  input: GFM

paginate: 5 # pagination based on number of posts
paginate_path: "blog/page/:num"

gems:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-sitemap

# Outputting
permalink: "/blog/:year/:month/:day/:title/"

# comments
disqus: nskoubou # add disqus shortname here

# author info
# add your appropriate info here
author: NV # your name
bio: 見習いセキュリティエンジニア # your bio
email: nvsofts@gmail.com
twitter_username: nvsofts
github_username: nvsofts

# Theming options
# These settings are mandatory.
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
