# Site settings
title: えぬえす工房
description: えぬえす工房
baseurl: ""
tags_path: "/blog/tags/"
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
highlighter: ""
paginate: 5 # pagination based on number of posts
paginate_path: "blog/page/:num"
excerpt_separator: "<!--more-->"
gems: 
  - jekyll-paginate
  - jekyll-coffeescript

# Outputting
permalink: "/blog/:year/:month/:day/:title/"

# comments
disqus: nskoubou # add disqus shortname here

# author info
# add your appropriate info here
author: NV # your name
bio: 見習いセキュリティエンジニア # your bio
email: nvsofts@gmail.com
email_md5: c6420a2a19f7a282192a2573597e96e2 # md5 hash of your email
twitter_username: nvsofts
github_username: nvsofts

# Theming options
# These settings are mandatory.
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
